### ISSUE TITLE
Activity/Sequence Diagram

### ISSUE THREAD

**Issue by joezed** [joezed/Software-Design-Imp#10]
it says plural on my notes but check assessment criteria to make sure if we need multiple or not

**Comment by joezed** [comment]
@SamLCrane @paulhavelin @RajalHussain If we could have a look at this next time we're in Info and Databases because its actually quite hard when Peters not telling you what to put 😞

**Comment by pedrombmachado** [comment]
@SamLCrane, @paulhavelin, @RajalHussain and @SamLCrane 
   I am encourage everyone to put the diagrams as a .png on the wiki. Hi found these two good tutorials [link1](https://guides.github.com/features/wikis/) and [link2](https://help.github.com/articles/about-github-wikis/). On the final submission you can reference the wiki.

**Comment by pedrombmachado** [comment]
Hi all,
  I am having trouble ope3ning your diagrams because I am linux user. Could you please export them into the PNG format and/or add them to the wiki?

**Comment by joezed** [comment]
completed!
