### ISSUE TITLE
Method Design

### ISSUE THREAD

**Issue by joezed** [joezed/Software-Design-Imp#20]

**Comment by paulhavelin** [comment]
@joezed @SamLCrane @RajalHussain 
'In software engineering, the template method pattern is a behavioral design pattern that defines the program skeleton of an algorithm in an operation, deferring some steps to subclasses.[1] It lets one redefine certain steps of an algorithm without changing the algorithm's structure.'

https://en.wikipedia.org/wiki/Template_method_pattern

**Comment by paulhavelin** [comment]
//DELETED - METHOD DESIGN AND PATTERNS IS IN THE SAME SECTION
