### ISSUE TITLE
Patterns and Method Design

### ISSUE THREAD

**Issue by joezed** [joezed/Software-Design-Imp#21]
???

**Comment by paulhavelin** [comment]
@joezed @SamLCrane @RajalHussain 
'In software engineering, a design pattern is a general reusable solution to a commonly occurring problem in software design. A design pattern is not a finished design that can be transformed directly into code. It is a description or template for how to solve a problem that can be used in many different situations.' 

https://en.wikibooks.org/wiki/Introduction_to_Software_Engineering/Architecture/Design_Patterns

**Comment by paulhavelin** [comment]
'In software engineering, the template method pattern is a behavioral design pattern that defines the program skeleton of an algorithm in an operation, deferring some steps to subclasses.[1] It lets one redefine certain steps of an algorithm without changing the algorithm's structure.'

https://en.wikipedia.org/wiki/Template_method_pattern

**Comment by paulhavelin** [comment]
@joezed @SamLCrane @RajalHussain 
patterns in a the code
 such as
----------------------------------------------------
Name: Accounts
Desc: The variable declarations for the accounts
-----------------------------------------------------

aForename = \\\\\\
aSurname =  \\\\\\
aPhoneNo = \\\\\\
ect.

(the lowercase 'a' at the start for accounts is a pattern - easy to understand by people who have never seen the code)
-----------------------------------------------------
Name: Booking
Desc: Booking Variables for the booking functions
------------------------------------------------------

bBookingName =  \\\\\\
bBookingTime=  \\\\\\
bBookingLocations =  \\\\\\

**Comment by paulhavelin** [comment]
adding finishing touches now - will upload to doc in next 10 mins
