### ISSUE TITLE
Test Cases

### ISSUE THREAD

**Issue by joezed** [joezed/Software-Design-Imp#27]

**Comment by joezed** [comment]
Created the template document, please add ones you come up with!

**Comment by paulhavelin** [comment]
@pedrombmachado 
Hi Pedro, currently working on the test cases, could you check we're going in the right direction with them
[doc/ -> 7.Appendix -> Test Cases.docx]

**Comment by pedrombmachado** [comment]
Hi @joezed ,
The tests should include the test type (qualitative/quantitative), the success criteria (How the test is consider valid/invalid, approved/rejected) and the procedure to be followed if the test fails. Please consider to create routines to test automatically the code and print on the screen the test result.
