### ISSUE TITLE
Add dates to the milestones

### ISSUE THREAD

**Issue by pedrombmachado** [joezed/Software-Design-Imp#34]
Hi Guys,
   Please add dates to your milestones.
Many thanks,
Pedro

**Comment by joezed** [comment]
Added deadlines to the documentation milestones for now as we know to get that finished before easter. Allowing more freedom on software releases in the knowledge we're all working towards the same goal.

**Comment by pedrombmachado** [comment]
@Joezed,
  I have uploaded a new version of the Programming Milestones.docx with my comments.
