### ISSUE TITLE
Algorithm Write Up

### ISSUE THREAD

**Issue by paulhavelin** [joezed/Software-Design-Imp#46]
among the algorithms studied in the lectures, choose (at least) one
adequate for your application and justify your choice. Explain how the
algorithm will work within your system and detail its steps.

**Comment by paulhavelin** [comment]
@pedrombmachado hi Pedro, could you check the write up for the sorting algorithm 

(doc/-> 3.Approach -> Sorting Algorithm.docx)

**Comment by pedrombmachado** [comment]
Hi @paulhavelin ,
   I am not sure if the Bubble Sort is the best option. You may want to consider using the quick, heap or merge. Check out this [link](https://www.toptal.com/developers/sorting-algorithms)

**Comment by paulhavelin** [comment]
sorting algorithm updated to Quicksort - added to /doc

searching algorithm  added to /doc - binary search tree

@pedrombmachado hi pedro could you check the updated sorting algorithm and searching algorthim write up

[doc] -> [3.Approach] -> Searching Algorithm.docx AND SortingAlgorithm NEW.docx
