### ISSUE TITLE
Text Based Use Cases

### ISSUE THREAD

**Issue by paulhavelin** [joezed/Software-Design-Imp#51]
convert use case diagram into text based

**Comment by paulhavelin** [comment]
doing the text use cases, could everyone help finish a few as its not hard, just time consuming leaving more  time for finalising code.
@SamLCrane @joezed @RajalHussain 
[doc/ -> 2.Requirements -> TEXT use cases

**Comment by paulhavelin** [comment]
@pedrombmachado hi pedro could these text use cases are correct with corrections to the use case diagram.

[doc] -> [2.Requirements] -> [TEXT Use cases v4]

**Comment by pedrombmachado** [comment]
@paulhavelin ,
   This new version looks better. It is now clear most of the steps that I can think of.

**Comment by paulhavelin** [comment]
just need to add Alternative flows to each
